[package]
name = "tamween"
version = "0.1.0"
edition = "2021"
description = "نظام إدارة وتشغيل محل التموين"
authors = ["Ali Seleem"]
publish = false

[lib]
name = "tamween_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tamween-core = { path = "../core" }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
